version: "2.12.2"
services:
    api:
        image: "wanikatako/basic_fastapi_docker"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
#        database:
#            image: mysql
